### ISSUE TITLE
Documentation: No clue how to run the application

### ISSUE THREAD

**Issue by elmdecoste** [agentlabs-inc/agentlabs#7]
Hey y'all, super interested in what you're working on. I cloned the repo to run it locally and see what's up, but there is not really any documentation surrounding what scripts to run and how to get it running properly. Updating the Readme with steps to run would be super helpful.

Some other helpful points of documentation: 
* What environment variables need to be set and where (especially for the frontend)
* Which scripts to run when
* The exact docker commands to run for the different environments (dev vs cloud)

Note: I get it seemingly close to running but when I go to localhost:8080 it white-screen-of-deaths on the `/main` route

Thanks y'all!

**Comment by kevinpiac** [comment]
Hey there!

Thanks for pointing this out and for the interest you put in AgentLabs 😃 

As specified in the README, the repository is under active development and not really at a stage where you could use it. That's the reason why there's no documentation at the moment because it would not make sense that anyone runs the project at this stage.

That being said, good news is we're actively building this and we plan to rollout an alpha version really soon!

Everything will be documented and running the project will be as simple as changing some environment variables and launching `docker-compose up`. 

We'll also provide a cloud-based version for those who wanna quickly test or use the product without dealing with this.

Thanks again for your issue, it's motivating to see that people are eager for this project 🚀

And feel free to reach our anytime 👍

**Comment by kevinpiac** [comment]
Just added more info in the README to make it clearer 😃 

https://github.com/agentlabs-inc/agentlabs#alpha-release

**Comment by 360macky** [comment]
> Just added more info in the README to make it clearer 😃
> 
> https://github.com/agentlabs-inc/agentlabs#alpha-release

Great! Hey, I'd love to see a video demo of this 😄. I'm doing my best to run AgentLabs on local.
